# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"

  # this way you will use default key that come with vagrant and not create new key inside machine - good for test purpose
  config.ssh.insert_key = false

  # Tell vagrant what folder to use
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # this way you protect your machine from dying, you reduce resource used by vagrant
  config.vm.provider :virtualbox do |v|
    v.memory = 256
    v.linked_clone = true
  
  end

  # App Server 1:
  config.vm.define "app14" do |app|
    app.vm.hostname = "orc-app1.test"
    app.vm.network :private_network, ip: "192.168.60.4"
  end
  # App Server 2:
  config.vm.define "app24" do |app|
    app.vm.hostname = "orc-app2.test"
    app.vm.network :private_network, ip: "192.168.60.5"
  end
  # App Server 1:
  config.vm.define "db4" do |db|
    db.vm.hostname = "orc-db.test"
    db.vm.network :private_network, ip: "192.168.60.6"
  end

end
