---
- name: Verify cluster resources
  hosts: localhost
  connection: local

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'

  tasks:
    - name: Get tower Pod data
      k8s_info:
        kind: Pod
        namespace: example-tower
        label_selectors:
          - app=tower
      register: tower_pods

    - name: Verify there is one tower pod
      assert:
        that: '{{ (tower_pods.resources | length) == 1 }}'
