---
- hosts: 127.0.0.1
  gather_facts: no
  connection: local

# Variable used to triger each of tests:

  vars:
    should_fail_via_fail: false
    should_fail_via_assert: true
    should_fail_via_complex_assert: true

  tasks:
    - name: Fail if conditions warrant a failure.
      fail:
        msg: "epic failure"
      when: should_fail_via_fail

    - name: Stop playbook if an assetion isnt validated.
      assert:
        that: "should_fail_via_assert != true"

    - name: Assertion can have contain conditions.
      assert:
        that:
          - should_fail_via_fail != true
          - should_fail_via_assert != true
          - should_fail_via_complex_assert != true
